// LIMITS — FONTE ÚNICA de bounds (§6). E5 fará LIMITS → Zod → HTML.
// Limites técnicos de dose = integridade numérica; NÃO são orientação clínica.
export const DOMAIN_LIMITS = { HALF_LIFE_MS_MIN: 1 } as const

export const SAFETY_LIMITS = {
  CONFIG_PAYLOAD_BYTES_MAX: 15_728_640,
  CONFIG_IMPORT_BYTES_MAX: 16_777_216,
  CALCULATION_RECORD_BYTES_MAX: 8_388_608,
  HISTORY_TOTAL_BYTES_MAX: 49_283_072,
  FULL_BACKUP_IMPORT_BYTES_MAX: 67_108_864,
  SCENARIOS_MAX: 20,
  DOSES_PER_SCENARIO_MAX: 2000,
  PROTOCOLS_MAX: 200,
  PROTOCOL_COMPONENTS_MAX: 20,
  WEEKS_MAX: 520,
  HISTORY_RECORDS_MAX: 500,
  QUARANTINE_ITEMS_MAX: 5,
  QUARANTINE_ITEM_BYTES_MAX: 262_144,
  QUARANTINE_TOTAL_BYTES_MAX: 1_048_576,
  HALF_LIFE_DAYS_MAX: 3650,
  TMAX_DAYS_MAX: 3650,
  RECON_VIAL_MASS_MG_MAX: 100_000,
  RECON_DILUENT_ML_MAX: 1000,
  RECON_DOSE_MCG_MAX: 1_000_000,
  SYRINGE_GRADUATION_UNITS_MAX: 100,
  SIMULATION_DOSE_MG_MAX: 1_000_000,
  PROTOCOL_TOTAL_DOSE_MG_MAX: 1_000_000,
} as const

export const UX_LIMITS = {
  NAME_MAX_CHARS: 100,
  FAVORITES_MAX: 100,
  GRADUATION_ERROR_WARN_THRESHOLD: 0.05,
} as const

import { MS_PER_DAY } from '../domain/units/convert'

// Constantes derivadas diretamente dos limites normativos (sem magic numbers).
export { MS_PER_DAY }
export const HALF_LIFE_MS_MAX = SAFETY_LIMITS.HALF_LIFE_DAYS_MAX * MS_PER_DAY
export const TMAX_MS_MAX = SAFETY_LIMITS.TMAX_DAYS_MAX * MS_PER_DAY

